app:
  env: local # local, production, testing
  theme: homer # homer, inspinia
  url: 'http://ci3ng.local'
  imports:
  - { resource: custom.yml }

db:
  default: mysql
  connections:
    mysql:
      driver: pdo_mysql
      host: localhost
      dbname: forge
      user: forge
      password:
      prefix: tbl_

mail:
  driver: smtp
  host: smtp.mailgun.org
  port: 587
  from:
    address: hello@example.com
    name: Example
  encryption: tls
  username:
  password:
  sendmail: /usr/sbin/sendmail -bs

orm:
  metadata:
    paths:
    - %base_path%/../shared/Modules/Account/Entities
    - %base_path%/../shared/Modules/System/Entities
  proxy_classes:
    directory: %base_path%/cache/proxies

paths:
  api: %base_path%/../../public/api
  uploads: %base_path%/../../public/uploads

session:
  cookie: ci3ng_session
  domain:

urls:
  api: %base_url%/api
  reset: %base_url%/#/reset?k=
