app:
  debug: %^APP_DEBUG%
  env: %^APP_ENV% # local, production, testing
  key: %^APP_KEY%
  theme: homer # homer, inspinia
  url: %^APP_URL%
  imports:
  - { resource: custom.yml }

db:
  default: mysql
  connections:
    mysql:
      driver: %^DB_DRIVER%
      host: %^DB_HOST%
      port: %^DB_PORT%
      dbname: %^DB_DATABASE%
      user: %^DB_USERNAME%
      password:
      prefix: %^DB_TABLE_PREFIX%

mail:
  driver: %^MAIL_DRIVER%
  host: %^MAIL_HOST%
  port: %^MAIL_PORT%
  from:
    address: hello@example.com
    name: Example
  encryption: %^MAIL_ENCRYPTION%
  username:
  password:
  sendmail: /usr/sbin/sendmail -bs

orm:
  cache:
    file:
      directory: %base_path%/cache/data
  metadata:
    paths:
    - %base_path%/../shared/Modules/Account/Entities
    - %base_path%/../shared/Modules/System/Entities
  proxy_classes:
    directory: %base_path%/cache/proxies

paths:
  api: %base_path%/../../public/api
  uploads: %base_path%/../../public/uploads

session:
  cookie: %^COOKIE_PREFIX%_session
  domain: %^COOKIE_DOMAIN%

urls:
  api: %base_url%/api
  reset: %base_url%/#/reset?k=
