services:
  Account\Entities\Permission:
    class:  Account\Entities\Permission
    shared: false
  Account\Events\PermissionListener:
    class:  Account\Events\PermissionListener
  Account\Services\PermissionService:
    class:  Account\Services\PermissionService
  Permission: '@Account\Entities\Permission'
  PermissionService: '@Account\Services\PermissionService'

  Account\Entities\Role:
    class:  Account\Entities\Role
    shared: false
  Account\Events\RoleListener:
    class:  Account\Events\RoleListener
  Account\Services\RoleService:
    class:  Account\Services\RoleService
  Role: '@Account\Entities\Role'
  RoleService: '@Account\Services\RoleService'

  Account\Entities\User:
    class:  Account\Entities\User
    shared: false
  Account\Events\UserListener:
    class:  Account\Events\UserListener
  Account\Services\UserService:
    class:  Account\Services\UserService
  User: '@Account\Entities\User'
  UserService: '@Account\Services\UserService'

  Account\Entities\UserRole:
    class:  Account\Entities\UserRole
    shared: false
  Account\Events\UserRoleListener:
    class:  Account\Events\UserRoleListener
  Account\Services\UserRoleService:
    class:  Account\Services\UserRoleService
  UserRole: '@Account\Entities\UserRole'
  UserRoleService: '@Account\Services\UserRoleService'
