#!/usr/bin/env sh

echo
echo "Setting environment variables ..."
if [ "$1" == "-p" ]; then
    cp ../deploys/20151217/production/.env .env
else
    if [ ! -f .env ]; then
        cp ../deploys/20151217/local/.env .env
    fi
fi

echo
if [ "$1" == "-f" ] || [ "$1" == "-p" ]; then
    vendor/bin/doctrine orm:schema-tool:drop --force
fi
vendor/bin/doctrine orm:schema-tool:update --force

echo
echo "Generating proxies ..."
if [ "$1" == "-f" ] || [ "$1" == "-p" ]; then
    ls application/system/cache/proxies/* | grep -v .gitignore | xargs rm -f
fi
vendor/bin/doctrine orm:generate:proxies

echo
echo "Deleting temporary files ..."
ls application/system/cache/data/* | grep -v .gitignore | xargs rm -f
ls application/system/cache/sessions/* | grep -v .gitignore | xargs rm -f
ls application/system/cache/vars/* | grep -v .gitignore | xargs rm -f
ls application/system/logs/* | grep -v .gitignore | xargs rm -f
